### ISSUE TITLE
Broken reasoner tests due to hard coded model path

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#140]
I got his when trying to run the tests locally. The failing tests also block the Gradle build. I need to figure out a way to exclude them.

```
Exception in thread "Thread-333" com.hp.hpl.jena.shared.WrappedIOException: java.io.FileNotFoundException: /E:/crapo/workspaceSadlGEOnlyDistrib/com.ge.research.sadl.jena-wrapper-for-sadl/src/test/resources/DataModels/Shapes/OwlModels/Rule.owl (No such file or directory)
	at com.hp.hpl.jena.rdf.model.impl.ModelCom.read(ModelCom.java:263)
	at com.hp.hpl.jena.ontology.impl.OntModelImpl.readDelegate(OntModelImpl.java:3109)
	at com.hp.hpl.jena.ontology.impl.OntModelImpl.read(OntModelImpl.java:2206)
	at com.hp.hpl.jena.ontology.impl.OntModelImpl.read(OntModelImpl.java:2122)
	at com.ge.research.sadl.jena.multithreaded.JenaBareThread.run(JenaBareThread.java:73)
Caused by: java.io.FileNotFoundException: /E:/crapo/workspaceSadlGEOnlyDistrib/com.ge.research.sadl.jena-wrapper-for-sadl/src/test/resources/DataModels/Shapes/OwlModels/Rule.owl (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1045)
	at com.hp.hpl.jena.rdf.model.impl.ModelCom.read(ModelCom.java:260)
	... 4 more
Exception in thread "Thread-299" com.hp.hpl.jena.shared.WrappedIOException: java.io.FileNotFoundException: /E:/crapo/workspaceSadlGEOnlyDistrib/com.ge.research.sadl.jena-wrapper-for-sadl/src/test/resources/DataModels/Shapes/OwlModels/Rule.owl (No such file or directory)
	at com.hp.hpl.jena.rdf.model.impl.ModelCom.read(ModelCom.java:263)
	at com.hp.hpl.jena.ontology.impl.OntModelImpl.readDelegate(OntModelImpl.java:3109)
	at com.hp.hpl.jena.ontology.impl.OntModelImpl.read(OntModelImpl.java:2206)
	at com.hp.hpl.jena.ontology.impl.OntModelImpl.read(OntModelImpl.java:2122)
	at com.ge.research.sadl.jena.multithreaded.JenaBareThread.run(JenaBareThread.java:73)
Caused by: java.io.FileNotFoundException: /E:/crapo/workspaceSadlGEOnlyDistrib/com.ge.research.sadl.jena-wrapper-for-sadl/src/test/resources/DataModels/Shapes/OwlModels/Rule.owl (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1045)
	at com.hp.hpl.jena.rdf.model.impl.ModelCom.read(ModelCom.java:260)
	... 4 more
```

**Comment by kittaakos** [comment]
https://github.com/crapo/sadlos2/commit/71bf3da783f27968490ba40c96ccec22711ea00f

**Comment by kittaakos** [comment]
> I need to figure out a way to exclude them.

I have disabled the tests from Gradle. The tests are still executed from Maven and the development environment.

**Comment by kittaakos** [comment]
I cannot see this error in the logs anymore. I am closing this issue.
