### ISSUE TITLE
Failing tests: CopyQualifiedNameServiceTest

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#142]
The new tests in the sadl.ui.tests project all fail. The error when run on a single test is:
java.lang.AssertionError: Expected running platform for content assist test.
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.ge.research.sadl.ui.tests.editor.CopyQualifiedNameServiceTest.createProject(CopyQualifiedNameServiceTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

java.lang.IllegalStateException: Workspace is closed.
	at org.eclipse.core.resources.ResourcesPlugin.getWorkspace(ResourcesPlugin.java:399)
	at org.eclipse.xtext.junit4.ui.util.IResourcesSetupUtil.root(IResourcesSetupUtil.java:43)
	at com.ge.research.sadl.ui.tests.editor.CopyQualifiedNameServiceTest.findProject(CopyQualifiedNameServiceTest.java:161)
	at com.ge.research.sadl.ui.tests.editor.CopyQualifiedNameServiceTest.deleteProject(CopyQualifiedNameServiceTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

The surefile report is:
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.986 sec <<< FAILURE! - in com.ge.research.sadl.ui.tests.editor.CopyQualifiedNameServiceTest
testAnotherCircle(com.ge.research.sadl.ui.tests.editor.CopyQualifiedNameServiceTest)  Time elapsed: 0.04 sec
testShape(com.ge.research.sadl.ui.tests.editor.CopyQualifiedNameServiceTest)  Time elapsed: 0.024 sec
testCircle(com.ge.research.sadl.ui.tests.editor.CopyQualifiedNameServiceTest)  Time elapsed: 0.009 sec  <<< FAILURE!
java.lang.AssertionError: expected:<http://sadl.org/Circle.sadl#Circle> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.ge.research.sadl.ui.tests.editor.CopyQualifiedNameServiceTest.testCircle(CopyQualifiedNameServiceTest.java:214)

testRadius(com.ge.research.sadl.ui.tests.editor.CopyQualifiedNameServiceTest)  Time elapsed: 0.03 sec

**Comment by kittaakos** [comment]
Good point, but I would say that is expected. Please try to execute the tests as `JUnit Plug-in Tests`.
Just like as described [here].

[here]: https://github.com/crapo/sadlos2/issues/134#issuecomment-268343259

**Comment by kittaakos** [comment]
I have changed the test setup, so it should be possible to run the tests as a `JUnit Test`. The PR is here: https://github.com/crapo/sadlos2/pull/143.

**Comment by kittaakos** [comment]
By the way, I have opened a [ticket] in xtext-eclipse, and proposed to move the service from UI to the core.

[ticket]: https://github.com/eclipse/xtext-eclipse/issues/145

**Comment by crapo** [comment]
Merged PR and works on Linux.
