### ISSUE TITLE
NPE in resource description strategy in case of a broken AST 

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#150]
```
uri "http://sadl.org/Foo.sadl".

foo is a class described by .
```

Exception:
```
!STACK 0
java.lang.NullPointerException
	at com.ge.research.sadl.scoping.QualifiedNameProvider.getFullyQualifiedName(QualifiedNameProvider.java:59)
	at com.ge.research.sadl.resource.ResourceDescriptionStrategy.createEObjectDescriptions(ResourceDescriptionStrategy.java:39)
	at org.eclipse.xtext.resource.impl.DefaultResourceDescription.computeExportedObjects(DefaultResourceDescription.java:89)
	at org.eclipse.xtext.resource.impl.DefaultResourceDescription$4.get(DefaultResourceDescription.java:179)
	at org.eclipse.xtext.resource.impl.DefaultResourceDescription$4.get(DefaultResourceDescription.java:173)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at org.eclipse.xtext.resource.impl.DefaultResourceDescription.getLookUp(DefaultResourceDescription.java:173)
	at org.eclipse.xtext.resource.impl.AbstractResourceDescription.getExportedObjects(AbstractResourceDescription.java:35)
	at org.eclipse.xtext.resource.impl.DefaultResourceDescriptionDelta.internalHasChanges(DefaultResourceDescriptionDelta.java:68)
	at org.eclipse.xtext.resource.impl.DefaultResourceDescriptionDelta.haveEObjectDescriptionsChanged(DefaultResourceDescriptionDelta.java:58)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport.haveEObjectDescriptionsChanged(DirtyStateEditorSupport.java:623)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport.announceDirtyState(DirtyStateEditorSupport.java:533)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.postParse(XtextDocumentReconcileStrategy.java:179)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.doReconcile(XtextDocumentReconcileStrategy.java:153)
	at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.reconcile(XtextDocumentReconcileStrategy.java:67)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.doRun(XtextReconciler.java:449)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.access$3(XtextReconciler.java:429)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:363)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:1)
	at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:37)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:428)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.internalModify(XtextDocument.java:162)
	at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.run(XtextReconciler.java:360)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```

**Comment by kittaakos** [comment]
I will take care of it.

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/151
