### ISSUE TITLE
Hard coded SADL IDE workspace location breaks application

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#156]
Currently, the workspace location is hard-coded in the shared launch configuration which breaks, for instance, the `OwlModels` folder creation. This change somehow got into the master branch. We need to restore it to the original state.

```
com.ge.research.sadl.reasoner.ConfigurationException: Unable to create model folder '/Users/akos.kitta/dev/Eclipse.app/Contents/MacOS/C::/Users/200005201/sadl3-master2/runtime-New_configuration/A/OwlModels'
	at com.ge.research.sadl.reasoner.ConfigurationManagerForEditing.validateModelFolderPath(ConfigurationManagerForEditing.java:1278)
	at com.ge.research.sadl.reasoner.ConfigurationManager.<init>(ConfigurationManager.java:150)
	at com.ge.research.sadl.reasoner.ConfigurationManagerForEditing.<init>(ConfigurationManagerForEditing.java:88)
	at com.ge.research.sadl.builder.ConfigurationManagerForIDE.<init>(ConfigurationManagerForIDE.java:110)
	at com.ge.research.sadl.builder.ConfigurationManagerForIdeFactory.getConfigurationManagerForIDE(ConfigurationManagerForIdeFactory.java:43)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.getConfigMgr(JenaBasedSadlModelProcessor.java:6183)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.prepareEmptyOntModel(JenaBasedSadlModelProcessor.java:1063)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.onValidate(JenaBasedSadlModelProcessor.java:666)
	at com.ge.research.sadl.processing.CompositeModelProcessor.lambda$0(CompositeModelProcessor.java:43)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.ge.research.sadl.processing.CompositeModelProcessor.onValidate(CompositeModelProcessor.java:45)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:64)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at com.ge.research.sadl.validation.ResourceValidator.lambda$0(ResourceValidator.java:49)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:51)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:91)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:520)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:86)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:67)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
```

**Comment by kittaakos** [comment]
I will take care of it.

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/157.

**Comment by crapo** [comment]
Akos will correct path to be OS-independent.

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/163
