### ISSUE TITLE
NPE when validating DSL with broken AST

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#170]
Besides having the good old, `Shapes`, `Rectangle` and `Circle` SADL models we have this test file:

```
uri "http://myUri".

import "http://circle".
import "http://rectangle". 

C is a Circle. 

C has a radius.
```

Exception:
```
!ENTRY org.apache.log4j 4 0 2017-04-05 09:14:41.124
!MESSAGE org.eclipse.xtext.validation.ResourceValidatorImpl  - Cannot convert node http://circle#radius to OntClass: it does not have rdf:type owl:Class or equivalent

!STACK 0
com.hp.hpl.jena.ontology.ConversionException: Cannot convert node http://circle#radius to OntClass: it does not have rdf:type owl:Class or equivalent
	at com.hp.hpl.jena.ontology.impl.OntClassImpl$1.wrap(OntClassImpl.java:83)
	at com.hp.hpl.jena.enhanced.EnhNode.convertTo(EnhNode.java:152)
	at com.hp.hpl.jena.enhanced.EnhNode.convertTo(EnhNode.java:31)
	at com.hp.hpl.jena.enhanced.Polymorphic.asInternal(Polymorphic.java:62)
	at com.hp.hpl.jena.enhanced.EnhNode.as(EnhNode.java:107)
	at com.hp.hpl.jena.ontology.impl.OntResourceImpl.asClass(OntResourceImpl.java:1160)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processSadlInstance(JenaBasedSadlModelProcessor.java:4269)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.onValidate(JenaBasedSadlModelProcessor.java:855)
	at com.ge.research.sadl.processing.CompositeModelProcessor.lambda$0(CompositeModelProcessor.java:45)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.ge.research.sadl.processing.CompositeModelProcessor.onValidate(CompositeModelProcessor.java:47)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:64)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at com.ge.research.sadl.validation.ResourceValidator.lambda$0(ResourceValidator.java:49)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:51)
	at org.eclipse.xtext.ui.validation.DefaultResourceUIValidatorExtension.addMarkers(DefaultResourceUIValidatorExtension.java:60)
	at org.eclipse.xtext.ui.validation.DefaultResourceUIValidatorExtension.updateValidationMarkers(DefaultResourceUIValidatorExtension.java:46)
	at org.eclipse.xtext.builder.builderState.MarkerUpdaterImpl.processDelta(MarkerUpdaterImpl.java:93)
	at org.eclipse.xtext.builder.builderState.MarkerUpdaterImpl.updateMarkers(MarkerUpdaterImpl.java:63)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.updateMarkers(AbstractBuilderState.java:82)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:283)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:287)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:267)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:161)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:733)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

```

**Comment by kittaakos** [comment]
I cannot reproduce it anymore. I am closing this issue.
