### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#196]
I have stumbled upon this error while I was building the p2 site for #193 

```
Results :

Tests in error: 
  SadlModelManagerProviderTest.myPropertyWithListsDeclarationCase:1027->assertValidatesTo:2034->lambda$23:1024 NullPointer

Tests run: 223, Failures: 0, Errors: 1, Skipped: 17
```

```
java.lang.NullPointerException: null
	at com.ge.research.sadl.tests.model.SadlModelManagerProviderTest.lambda$23(SadlModelManagerProviderTest.java:1024)
	at com.ge.research.sadl.tests.model.SadlModelManagerProviderTest.assertValidatesTo(SadlModelManagerProviderTest.java:2034)
	at com.ge.research.sadl.tests.model.SadlModelManagerProviderTest.myPropertyWithListsDeclarationCase(SadlModelManagerProviderTest.java:1027)
```

**Comment by kittaakos** [comment]
The above-mentioned test passes when running it from Eclipse.
I have tried:
 - to run it as an individual JUnit test.
 - run all test cases in the class.
 - did the same as a JUnit Plug-in test.

**Comment by kittaakos** [comment]
Now the test passes after re-running the maven build. I leave this task open.

**Comment by kittaakos** [comment]
I have not encountered this test failure for weeks now. I am closing this ticket. One can reopen it if the same problem occurs again.
