### ISSUE TITLE
Linking issues related to Jena

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#23]
I am still not able to run as IDE, nor is Aaron I believe. When I try to run/debug as Eclipse Application I get problems related to resolving classes as shown in stack trace below. This appears to be because of inconsistency in versions of jars. To include everything Jena needs, can we not use the Maven dependency? From another Maven project, It should be (actually, the second and third dependencies may be implied in the first?):
  	<dependency>
  		<groupId>org.apache.jena</groupId>
  		<artifactId>apache-jena-libs</artifactId>
  		<version>2.13.0</version>
  		<type>pom</type>
  		<exclusions>
  			<exclusion>
  				<groupId>log4j</groupId>
  				<artifactId>log4j</artifactId>
  			</exclusion>
  		</exclusions>
  	</dependency>
	<dependency>
	    <groupId>org.apache.jena</groupId>
	    <artifactId>jena-arq</artifactId>
	    <version>2.13.0</version>
	</dependency>
	<dependency>
		<groupId>org.apache.jena</groupId>
		<artifactId>jena-core</artifactId>
		<version>2.13.0</version>
	</dependency>

**** the error****
java.lang.ExceptionInInitializerError
	at com.hp.hpl.jena.rdf.model.impl.RDFReaderFImpl.reset(RDFReaderFImpl.java:82)
	at com.hp.hpl.jena.rdf.model.impl.RDFReaderFImpl.<clinit>(RDFReaderFImpl.java:75)
	at com.hp.hpl.jena.rdf.model.impl.ModelCom.<clinit>(ModelCom.java:54)
	at com.hp.hpl.jena.rdf.model.ModelFactory.createDefaultModel(ModelFactory.java:140)
	at com.hp.hpl.jena.vocabulary.OWL.<clinit>(OWL.java:36)
	at com.hp.hpl.jena.ontology.ProfileRegistry.<clinit>(ProfileRegistry.java:43)
	at com.hp.hpl.jena.ontology.OntModelSpec.<clinit>(OntModelSpec.java:49)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.onValidate(JenaBasedSadlModelProcessor.java:126)
	...
Caused by: java.lang.ClassCastException: org.apache.xerces.jaxp.DocumentBuilderFactoryImpl cannot be cast to javax.xml.parsers.DocumentBuilderFactory
	at javax.xml.parsers.DocumentBuilderFactory.newInstance(Unknown Source)
	at java.util.XMLUtils.getLoadingDoc(Unknown Source)
	at java.util.XMLUtils.load(Unknown Source)
	at java.util.Properties.loadFromXML(Unknown Source)
	at com.hp.hpl.jena.util.Metadata.read(Metadata.java:76)
	at com.hp.hpl.jena.util.Metadata.addMetadata(Metadata.java:54)
	at com.hp.hpl.jena.util.Metadata.<init>(Metadata.java:48)
	at com.hp.hpl.jena.JenaRuntime.<clinit>(JenaRuntime.java:34)

**Comment by svenefftinge** [comment]
The xerces lib needs to be taken from an OSGI bundle. Otherwise we and up with identity problems for xml classes that come from xml-apis and those from the parent classloader (the JDK)

After checking out you need to refresh the target platform in the preferences.
