### ISSUE TITLE
NPE in Jena based SADL model processor when validating broken AST

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#232]
`I1.sadl`
```
uri "http://sadl.org/I1.sadl" alias I1.
Foo is a class.
```

`I2.sadl`
```
uri "http://sadl.org/I2.sadl" alias I2.
Foo is a class.
```

`Current.sadl`
```
uri "http://sadl.org/Current.sadl" alias current.
import "http://sadl.org/I1.sadl" as i1.
import "http://sadl.org/I2.sadl" as i2.

Foo is a

Bar is a type of i2:Foo.
Baz is a type of i1:Foo.
```

`Stack trace:`
```
java.lang.NullPointerException
	at com.ge.research.sadl.model.DeclarationExtensions.getOntConceptType(DeclarationExtensions.java:527)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processSadlInstance(JenaBasedSadlModelProcessor.java:5295)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.onValidate(JenaBasedSadlModelProcessor.java:995)
	at com.ge.research.sadl.processing.CompositeModelProcessor.lambda$0(CompositeModelProcessor.java:47)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.ge.research.sadl.processing.CompositeModelProcessor.onValidate(CompositeModelProcessor.java:49)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:69)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at com.ge.research.sadl.validation.ResourceValidator.lambda$0(ResourceValidator.java:54)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:56)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:91)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:520)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:86)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:67)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

```

**Comment by crapo** [comment]
I created the models exactly as shown but could not reproduce. Perhaps this is no longer an issue, or perhaps some particular sequence is necessary?

**Comment by kittaakos** [comment]
I have to double check, I was working on a branch.

**Comment by kittaakos** [comment]
Cannot reproduce it anymore. Closing issue.
