### ISSUE TITLE
Multiple calls to model processor for the same resource in UI test

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#269]
I created a new sadl.ui.test test file, SadlModelArticleTest.xtend. It has a test case that passes on one preference setting and fails on another. In the failing case there are two sets of the two issues I expect because the model processor is run twice for the resource. The test is closely fashioned after the SadlIgnoreUnittedQuantityTest.
Note also that for either test there are exceptions NPEs thrown that probably weren't there previously? Not entirely sure why that is happening...

java.lang.NullPointerException
	at com.ge.aviation.sadl.requirements.resourcechangelistener.PreDirectWriteListener.resourceChanged(PreDirectWriteListener.java:151)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:382)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:523)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:423)
	at org.eclipse.xtext.junit4.ui.util.IResourcesSetupUtil.waitForBuild(IResourcesSetupUtil.java:328)
	at org.eclipse.xtext.junit4.ui.util.IResourcesSetupUtil.waitForBuild(IResourcesSetupUtil.java:323)
	at com.ge.research.sadl.ui.tests.AbstractSadlPlatformTest.deleteProjects(AbstractSadlPlatformTest.java:172)
	at com.ge.research.sadl.ui.tests.AbstractSadlPlatformTest.after(AbstractSadlPlatformTest.java:113)

**Comment by kittaakos** [comment]
I have renamed the test to SadlModelArticleUITest. We already had SadlModelArticleTest in the core. See: 18c1786152098d81796086655dde4fe6bb32f067

**Comment by kittaakos** [comment]
I have no idea, why the SRL resource change listener runs for you. It could be due to the opened SRL projects in your WS. I need to check that.

**Comment by kittaakos** [comment]
Strange, both article tests are green here. I cannot see any NPEs in the log. Could you please pull my changes and verify it once more? Or maybe I just did not understand the problem here.

**Comment by kittaakos** [comment]
That explains. I will adjust the test expectations.

**Comment by kittaakos** [comment]
> I will adjust the test expectations.

e315d40db257db5658185271c8b17f79ac6025a8

**Comment by crapo** [comment]
I modified the abstract test class validation methods to use the model processor, since it is now there, instead of getting results of processing (other than OntModel) from the OntModelProvider. That very quickly restored all tests to passing.

I still get anNPE in the PreDirectWriteListener.resourceChanged but haven't looked into it yet.
