### ISSUE TITLE
We need a customized workspace for the Xtext language server

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#310]
It blindly casts the resources to an XtextResource which does not work well with the external EMF resources:
```
SEVERE: Internal error: java.lang.ClassCastException: com.ge.research.sadl.external.ExternalEmfResource cannot be cast to org.eclipse.xtext.resource.XtextResource
java.util.concurrent.CompletionException: java.lang.ClassCastException: com.ge.research.sadl.external.ExternalEmfResource cannot be cast to org.eclipse.xtext.resource.XtextResource
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:43)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: com.ge.research.sadl.external.ExternalEmfResource cannot be cast to org.eclipse.xtext.resource.XtextResource
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:278)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$documentSymbol$35(LanguageServerImpl.java:609)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:37)
	... 4 more
```

**Comment by kittaakos** [comment]
Done.
