### ISSUE TITLE
Exception in CA

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#321]
```
uri "http://sadl.org/a.sadl".

Ask : "value"<|>
```

```
[2018-05-25T11:15:51.010Z] ERROR: Theia/1712 on Akoss-MacBook-Pro.local: (logger=root)
    SADL: May 25, 2018 1:15:51 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
    SEVERE: Internal error: java.lang.IllegalArgumentException: Unhandled parameter types: [com.ge.research.sadl.sADL.impl.QueryStatementImpl@42449a8a (start: Ask)]
    java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Unhandled parameter types: [com.ge.research.sadl.sADL.impl.QueryStatementImpl@42449a8a (start: Ask)]
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:43)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.IllegalArgumentException: Unhandled parameter types: [com.ge.research.sadl.sADL.impl.QueryStatementImpl@42449a8a (start: Ask)]
        at com.ge.research.sadl.ide.editor.contentassist.SadlOntologyContextProvider.getSubjHasPropInitializer(SadlOntologyContextProvider.java:421)
        at com.ge.research.sadl.ide.editor.contentassist.SadlOntologyContextProvider.getOntologyContext(SadlOntologyContextProvider.java:271)
        at com.ge.research.sadl.ide.editor.contentassist.ProposalProviderFilterProvider.getCrossReferenceFilter(ProposalProviderFilterProvider.java:83)
        at com.ge.research.sadl.ide.editor.contentassist.SadlIdeContentProposalProvider.lambda$lookupCrossReference$4(SadlIdeContentProposalProvider.java:498)
        at org.eclipse.xtext.ide.editor.contentassist.IdeCrossrefProposalProvider.lookupCrossReference(IdeCrossrefProposalProvider.java:58)
        at org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider._createProposals(IdeContentProposalProvider.java:180)
        at com.ge.research.sadl.ide.editor.contentassist.SadlIdeContentProposalProvider.createProposals(SadlIdeContentProposalProvider.java:807)
        at org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider._createProposals(IdeContentProposalProvider.java:110)
        at com.ge.research.sadl.ide.editor.contentassist.SadlIdeContentProposalProvider._createProposals(SadlIdeContentProposalProvider.java:157)
        at com.ge.research.sadl.ide.editor.contentassist.SadlIdeContentProposalProvider.createProposals(SadlIdeContentProposalProvider.java:804)
        at org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider.createProposals(IdeContentProposalProvider.java:94)
        at org.eclipse.xtext.ide.server.contentassist.ContentAssistService.createProposals(ContentAssistService.java:108)
        at org.eclipse.xtext.ide.server.contentassist.ContentAssistService.createCompletionList(ContentAssistService.java:73)
        at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$completion$29(LanguageServerImpl.java:541)
        at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:283)
        at org.eclipse.xtext.ide.server.LanguageServerImpl.completion(LanguageServerImpl.java:543)
        at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$completion$28(LanguageServerImpl.java:522)
        at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:37)
        ... 4 more
```

**Comment by kittaakos** [comment]
Fixed with #292.
