### ISSUE TITLE
The Maven build fails due to Java SecurityException: signer information does not match

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#326]
I wiped my Maven repositories and ran `mvn -D clean verify` on the HEAD (`git rev-parse --short HEAD` -> 7973a05d) of the `master` branch. By the way, the same happens on the `development` (afea61af) branch too.

```
[ERROR] Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:2.11.0:compile (default) on project com.ge.research.sadl.xtextgenerator: Execution default of goal org.eclipse.xtend:xtend-maven-plugin:2.11.0:compile failed: Unable to load the mojo 'compile' (or one of its required components) from the plugin 'org.eclipse.xtend:xtend-maven-plugin:2.11.0': com.google.inject.ProvisionException: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) Error injecting constructor, com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: java.lang.SecurityException: class "org.eclipse.core.runtime.OperationCanceledException"'s signer information does not match signer information of other classes in the same package
[ERROR]   at org.eclipse.xtend.maven.XtendCompile.<init>(Unknown Source)
[ERROR]   while locating org.eclipse.xtend.maven.XtendCompile
[ERROR]   at ClassRealm[plugin>org.eclipse.xtend:xtend-maven-plugin:2.11.0, parent: sun.misc.Launcher$AppClassLoader@42a57993] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
[ERROR]   while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=org.eclipse.xtend:xtend-maven-plugin:2.11.0:compile)
[ERROR] 
[ERROR] 1 error
[ERROR]       role: org.apache.maven.plugin.Mojo
[ERROR]   roleHint: org.eclipse.xtend:xtend-maven-plugin:2.11.0:compile
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :com.ge.research.sadl.xtextgenerator

```

Full console log:
[sadl-mvn-clean-verify-master.txt](https://github.com/crapo/sadlos2/files/2148350/sadl-mvn-clean-verify-master.txt)

**Comment by kittaakos** [comment]
This could be related: https://bugs.eclipse.org/bugs/show_bug.cgi?id=483338

**Comment by kittaakos** [comment]
This: https://github.com/eclipse/xtext/issues/1231

**Comment by zacharydavidr** [comment]
> This: eclipse/xtext#1231

Used the workaround to mentioned by cdietrich that includes replacing the plugin definition in all our pom files with the definition he provided. Our builds pass with this workaround. Looks like it adds a  dependency for org.eclipse.equinox.common, at least that's the result after changing our pom files.

**Comment by kittaakos** [comment]
> Our builds pass with this workaround.

I am still trying to get the build pass locally. It is failing with the following error.
```
1    ERROR Mwe2Launcher       - [XtextLinkingDiagnostic: null:69 Couldn't resolve reference to JvmIdentifiableElement 'name'., XtextLinkingDiagnostic: null:70 Couldn't resolve reference to JvmIdentifiableElement 'fileExtensions'., XtextLinkingDiagnostic: null:72 Couldn'tresolve reference to JvmIdentifiableElement 'parserGenerator'., XtextLinkingDiagnostic: null:73 Couldn't resolve reference to JvmIdentifiableElement 'debugGrammar'., XtextLinkingDiagnostic: null:74 Couldn't resolve reference to JvmIdentifiableElement 'combinedGrammar'., XtextLinkingDiagnostic: null:76 Couldn't resolve reference to JvmIdentifiableElement 'serializer'., XtextLinkingDiagnostic: null:78 Couldn't resolve reference to JvmIdentifiableElement 'generateStub'., XtextLinkingDiagnostic: null:80 Couldn't resolve reference to JvmIdentifiableElement 'validator'., XtextLinkingDiagnostic: null:84 Couldn't resolve reference to JvmIdentifiableElement 'fragment'.]
java.lang.IllegalStateException: [XtextLinkingDiagnostic: null:69 Couldn't resolve reference to JvmIdentifiableElement 'name'., XtextLinkingDiagnostic: null:70 Couldn't resolve reference to JvmIdentifiableElement 'fileExtensions'., XtextLinkingDiagnostic: null:72 Couldn't resolve reference to JvmIdentifiableElement 'parserGenerator'., XtextLinkingDiagnostic: null:73 Couldn't resolve reference to JvmIdentifiableElement 'debugGrammar'., XtextLinkingDiagnostic: null:74 Couldn't resolve reference to JvmIdentifiableElement 'combinedGrammar'.,XtextLinkingDiagnostic: null:76 Couldn't resolve reference to JvmIdentifiableElement 'serializer'., XtextLinkingDiagnostic: null:78 Couldn't resolve reference to JvmIdentifiableElement 'generateStub'., XtextLinkingDiagnostic: null:80 Couldn't resolve reference to JvmIdentifiableElement 'validator'., XtextLinkingDiagnostic: null:84 Couldn't resolve reference to JvmIdentifiableElement 'fragment'.]
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:88)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:62)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:52)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
        at java.lang.Thread.run(Thread.java:745)
```

@zacharydavidr, please confirm; can you proceed with the workaround? Thanks!

**Comment by zacharydavidr** [comment]
I deleted my .m2 repository again and forced new downloads of everything. I'm still getting a passing build on saldos2. I'm running our project again just to make sure, but right now it looks like we can proceed.

**Comment by kittaakos** [comment]
> projects is still passing as well.

Awesome. Thanks for the verification.

I am closing this, please reopen if necessary.
