### ISSUE TITLE
IllegalArgumentException: Unhandled parameter types with broken AST

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#327]
Similar to #321.

```
uri "http://sadl.org/Test.sadl" alias Test.

Ask: x is a <|>.
```

The cursor is at `<|>`. Type any character:

```
Jul 19, 2018 2:49:22 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: Unhandled parameter types: [com.ge.research.sadl.sADL.impl.BinaryOperationImpl@79f7c6b8 (op: is)]
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Unhandled parameter types: [com.ge.research.sadl.sADL.impl.BinaryOperationImpl@79f7c6b8 (op: is)]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:43)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unhandled parameter types: [com.ge.research.sadl.sADL.impl.BinaryOperationImpl@79f7c6b8 (op: is)]
	at com.ge.research.sadl.ide.editor.contentassist.SadlOntologyContextProvider.getClassOrPropertyInitializer(SadlOntologyContextProvider.java:398)
	at com.ge.research.sadl.ide.editor.contentassist.SadlOntologyContextProvider.getOntologyContext(SadlOntologyContextProvider.java:187)
	at com.ge.research.sadl.ide.editor.contentassist.ProposalProviderFilterProvider.getCrossReferenceFilter(ProposalProviderFilterProvider.java:83)
	at com.ge.research.sadl.ide.editor.contentassist.SadlIdeContentProposalProvider.lambda$4(SadlIdeContentProposalProvider.java:498)
	at org.eclipse.xtext.ide.editor.contentassist.IdeCrossrefProposalProvider.lookupCrossReference(IdeCrossrefProposalProvider.java:58)
	at org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider._createProposals(IdeContentProposalProvider.java:180)
	at com.ge.research.sadl.ide.editor.contentassist.SadlIdeContentProposalProvider.createProposals(SadlIdeContentProposalProvider.java:807)
	at org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider._createProposals(IdeContentProposalProvider.java:110)
	at com.ge.research.sadl.ide.editor.contentassist.SadlIdeContentProposalProvider._createProposals(SadlIdeContentProposalProvider.java:157)
	at com.ge.research.sadl.ide.editor.contentassist.SadlIdeContentProposalProvider.createProposals(SadlIdeContentProposalProvider.java:804)
	at org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider.createProposals(IdeContentProposalProvider.java:94)
	at org.eclipse.xtext.ide.server.contentassist.ContentAssistService.createProposals(ContentAssistService.java:108)
	at org.eclipse.xtext.ide.server.contentassist.ContentAssistService.createCompletionList(ContentAssistService.java:73)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$completion$29(LanguageServerImpl.java:541)
	at com.ge.research.sadl.ide.lsp.extension.SadlWorkspaceManager.doRead(SadlWorkspaceManager.java:48)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.completion(LanguageServerImpl.java:543)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$completion$28(LanguageServerImpl.java:522)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$run$0(ReadRequest.java:37)
	... 4 more

```

**Comment by kittaakos** [comment]
Fixed with #292.
