### ISSUE TITLE
Error I don't understand after changes to get grammar keywords

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#335]
With changes in branch AWC-Grammar-BasedReservedWords (commit https://github.com/crapo/sadlos2/commit/b55d0c3054088e344e510bc96c01995a3af90e5c) the UI test case GH_275_CheckTranslatorAndInferencePluginTest.checkTranslatorOutput fails with error that I don't understand.
`java.lang.IllegalStateException: Passed org.eclipse.xtext.builder.clustering.CurrentDescriptions is not based on a resource set
	at org.eclipse.xtext.resource.containers.ResourceSetBasedAllContainersStateProvider.getResourceSet(ResourceSetBasedAllContainersStateProvider.java:44)
	at org.eclipse.xtext.resource.containers.ResourceSetBasedAllContainersStateProvider.get(ResourceSetBasedAllContainersStateProvider.java:26)
	at org.eclipse.xtext.resource.containers.StateBasedContainerManager.getState(StateBasedContainerManager.java:81)
	at org.eclipse.xtext.resource.containers.StateBasedContainerManager.internalGetContainerHandle(StateBasedContainerManager.java:106)
	at org.eclipse.xtext.resource.containers.StateBasedContainerManager.getVisibleContainers(StateBasedContainerManager.java:59)
	at com.ge.research.sadl.resource.SadlResourceDescriptionManager.isAffected(SadlResourceDescriptionManager.java:72)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.queueAffectedResources(ClusteringBuilderState.java:528)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:300)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:288)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:268)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:162)`

**Comment by kittaakos** [comment]
You should try to inject the `SADLParser` instead of creating an injector in the [static scope](https://github.com/crapo/sadlos2/commit/b55d0c3054088e344e510bc96c01995a3af90e5c#diff-00be580bebaf34917cfb6ac809e73015R10645) and acquiring a parser instance.

**Comment by crapo** [comment]
Does that mean that the method can't be static? The problem is that getSadlKeywords() is called by createBuiltinFunctionImplicitModel(String projectRootPath), which is static and is called from several places including the headless processing. So these static calls should create an instance of the JenaBasedSadlModelProcessor? Not sure how to deal with the static calls...

**Comment by kittaakos** [comment]
I am currently on
```
development  5ba48607 [origin/development] Add processed collection of literals to variable definition
```
and the `GH_275_CheckTranslatorAndInferencerPluginTest` tests pass. Please give me a branch I can check out to reproduce the issue.

**Comment by crapo** [comment]
This is on branch AWC-Grammar-BasedReservedWords as noted in the original issue post. I've pushed the partial update that I did to try to inject the SADLParser per you first comment, so the current code will have compile errors related to the static method calling a non-static method.

**Comment by kittaakos** [comment]
Unfortunately, in this commit (d2705e4834306dd14f5ed36645956cc76c328816), the URI building is broken on OS X.

There is no such URI on UNIX: `file://Users/akos.kitta/dev/wss/junit-workspace/resource`.
It should be `file:///Users/akos.kitta/dev/wss/junit-workspace/resource` instead. The above-mentioned commit results in 35 UI test failures from the 55. Is this something you want to take care of or I should fix it? If the latter one, I need to know what was the purpose of the change and what was wrong with the original logic. Once it is fixed, I can look into the original issue with the keywords. Thank you!

**Comment by crapo** [comment]
Since none of us have a Unix environment, if you are willing to fix this that would be great. Nick pushed the commit that broke the tests on Unix without knowing that it be an issue. My sense is that we already have code that converts platform URLs to file URLs in an OS-independent way, and that he could have used them. So it may just be replacing what he did with calls to existing functions or existing code refactored to reusable functions. Please let me know if you are able to do this. It would be charged to the older PO that is for ASSERT. The changes Nick made were to fix issues in the headless CLI, so he can test that once we think everything is corrected.

**Comment by kittaakos** [comment]
@crapo, I have created the PR with the changes: https://github.com/crapo/sadlos2/pull/338.

Could you please try this on your side too? All my tests, including the `GH_275_CheckTranslatorAndInferencePluginTest` were green locally.

It should be sufficient to push the `Merge pull request` button and the changes will be available on the `AWC-Grammar-BasedReservedWords` branch.

Let me know if you still have issues. Thank you!

**Comment by crapo** [comment]
Looks good. Thanks!!!
