### ISSUE TITLE
Grouped SADL preferences not working on project-specific settings

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#345]
Related to [https://github.com/crapo/sadlos2/issues/334](url)

I organized the SADL preferences using a org.eclipse.swt.widgets.Group but apparently that's incompatible with the org.eclipse.xtext.ui.editor.preferences.LanguageRootPreferencePage? It works for workspace preferences but if I try to go to project properties it chokes with message "The currently displayed page contains invalid values." 

org.eclipse.core.runtime.AssertionFailedException: assertion failed: Different parents
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:110)
	at org.eclipse.jface.preference.FieldEditor.checkParent(FieldEditor.java:170)
	at org.eclipse.jface.preference.FieldEditor.getLabelControl(FieldEditor.java:396)
	at org.eclipse.jface.preference.FieldEditor.setEnabled(FieldEditor.java:716)
	at org.eclipse.jface.preference.StringFieldEditor.setEnabled(StringFieldEditor.java:528)
	at org.eclipse.xtext.ui.editor.preferences.AbstractPreferencePage.updateFieldEditors(AbstractPreferencePage.java:296)
	at org.eclipse.xtext.ui.editor.preferences.AbstractPreferencePage.handleUseProjectSettings(AbstractPreferencePage.java:282)
	at org.eclipse.xtext.ui.editor.preferences.AbstractPreferencePage.createControl(AbstractPreferencePage.java:234)
	at org.eclipse.jface.preference.PreferenceDialog.createPageControl(PreferenceDialog.java:1502)
	at org.eclipse.jface.preference.PreferenceDialog$14.run(PreferenceDialog.java:1259)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:49)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:175)
	at org.eclipse.jface.preference.PreferenceDialog.showPage(PreferenceDialog.java:1253)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.showPage(FilteredPreferenceDialog.java:675)
	at org.eclipse.jface.preference.PreferenceDialog$10.run(PreferenceDialog.java:709)

**Comment by kittaakos** [comment]
I have set up [`GH-345`](https://github.com/crapo/sadlos2/tree/GH-345) from the [`AWC-ServicesConfig`](https://github.com/crapo/sadlos2/tree/AWC-ServicesConfig) branch for the development.

**Comment by kittaakos** [comment]
Steps to reproduce:
 - Right-click on the project in the `Project Explorer` > `Properties` > `SADL` > Error.
 - It does **not** happen when opening the preferences from `Preferences` (<kbd>Cmd</kbd>+<kbd>,</kbd> on macOS)> `SADL`.

@crapo, do you want me to fix the layout in the SADL preferences page or is this the desired layout?

![screen shot 2018-12-03 at 10 19 22](https://user-images.githubusercontent.com/1405703/49364608-fd73c800-f6e4-11e8-9e5f-57716ce4b8e9.jpg)

**Comment by kittaakos** [comment]
Corresponding change: https://github.com/crapo/sadlos2/commit/c68be1051e32e9feefbdce4744a540dce36dce45#diff-b6204f44f11a4a1f61c8634d5112922e

**Comment by kittaakos** [comment]
This seems to be an Xtext issue. [Here](https://github.com/eclipse/xtext-eclipse/blob/f75a21470af2b3f6252a86adb7af74f2af5423d9/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/preferences/AbstractPreferencePage.java#L234) is the difference. I am trying to reproduce this outside of SADL.

**Comment by GEGlobalResearch** [comment]
The layout isn't a desired layout. I was just trying to group the preferences and that layout was what came out. I don't understand how to make the layout better, but was first worried about the fact that it wasn't working at all for project-specific preferences.

**Comment by kittaakos** [comment]
Here is the upstream issue: https://github.com/eclipse/xtext-eclipse/issues/916

**Comment by kittaakos** [comment]
Xtext 2.16 does not support this use-case. We can implement this feature for Xtext, provide a PR and then we have to use 2.17 nightly. Let me know if this is what we want.

**Comment by GEGlobalResearch** [comment]
Would the implementation in Xtext be charged to our PO? If so, what is the estimated effort? What is your assessment of risk using 2.17 nightly and what is the estimated time until it would make it into an Xtext release?

**Comment by kittaakos** [comment]
@crapo, I managed to come up with an implementation that works for our needs without Xtext modifications. PR: https://github.com/crapo/sadlos2/pull/349

**Comment by crapo** [comment]
Great!! Thank you. I'll test.

**Comment by crapo** [comment]
Looks great!!
