### ISSUE TITLE
Jena model processor: NPE when Equation is broken in the AST

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#346]
```
uri "http://com.ge.research.sadl/equations".
	Equation add(decimal x,  y) returns decimal: x + y.
```

```
java.lang.NullPointerException
	at com.ge.research.sadl.model.gp.Equation.toFullyQualifiedString(Equation.java:256)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.createEquation(JenaBasedSadlModelProcessor.java:2858)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processStatement(JenaBasedSadlModelProcessor.java:2756)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processModelElement(JenaBasedSadlModelProcessor.java:1172)
	at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.onValidate(JenaBasedSadlModelProcessor.java:1078)
	at com.ge.research.sadl.validation.ResourceValidator.doValidate(ResourceValidator.java:76)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:72)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at com.ge.research.sadl.validation.ResourceValidator.lambda$0(ResourceValidator.java:56)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:76)
	at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:58)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:91)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:527)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:499)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:137)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:86)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:67)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
```

**Comment by crapo** [comment]
added checks, corrected extraction of arguments and argument types from EObjects.
