### ISSUE TITLE
recent logger changes break the LS build

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#353]
Steps to reproduce:
```bash
rm -rf sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ide/build/install/ \
&& rm -rf ./sadl3/com.ge.research.sadl.parent/theia-sadl-extension/sadl-extension/bin/ \
&& ./sadl3/com.ge.research.sadl.parent/gradlew -p ./sadl3/com.ge.research.sadl.parent/ build installDist --refresh-dependencies --stacktrace \
&& cp -rf ./sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ide/build/install/ ./sadl3/com.ge.research.sadl.parent/theia-sadl-extension/sadl-extension/bin/
```

```
Writing code to "/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/../com.ge.research.sadl/src-gen/com/ge/research/sadl/parser/antlr/lexer/jflex/SADLFlexer.java"
23864 [main] INFO  text.xtext.generator.XtextGenerator  - Generating common infrastructure
23880 [main] INFO  .emf.mwe2.runtime.workflow.Workflow  - Done.

> Task :com.ge.research.sadl:generateXtext
WARNING:Unnecessary cast from List<SadlMarkerRef> to List<SadlMarkerRef> (file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/markers/SadlMarker.xtend line : 38 column : 84)
WARNING:The def modifier is unnecessary on method getEObjectByName (file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/markers/SadlMarkerLocationProvider.xtend line : 93 column : 12)
WARNING:The public modifier is unnecessary on class SadlMarkerConstants (file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/markers/SadlMarkerConstants.xtend line : 25 column : 1)
WARNING:Superfluous @Override annotation (file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/SadlImportProcessorProvider.xtend line : 44 column : 2)
WARNING:Superfluous @Override annotation (file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/SadlImportProcessorProvider.xtend line : 55 column : 2)
WARNING:The private modifier is unnecessary on field processor (file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/SadlImportProcessorProvider.xtend line : 36 column : 3)
WARNING:Superfluous @Override annotation (file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/SadlOntologyHelper.xtend line : 31 column : 2)
WARNING:Superfluous @Override annotation (file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/ValidationAcceptor.xtend line : 37 column : 3)
WARNING:The expression of type SadlResource is already of type SadlResource (file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/scoping/SADLScopeProvider.xtend line : 220 column : 8)
WARNING:The expression of type SadlResource is already of type SadlResource (file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/scoping/SADLScopeProvider.xtend line : 220 column : 8)
ERROR:org.eclipse.xtext.builder.clustering.CurrentDescriptions cannot be resolved to a type. (file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/SADLRuntimeModule.xtend line : 36 column : 8)
ERROR:CurrentDescriptions cannot be resolved to a type. (file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/SADLRuntimeModule.xtend line : 74 column : 5)
ERROR:The method getTarget() is undefined for the type IResourceDescriptions (file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/SADLRuntimeModule.xtend line : 75 column : 27)
WARNING:Superfluous @Override annotation (file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/generator/SADLOutputConfigurationProvider.xtend line : 36 column : 2)
WARNING:Unnecessary cast from SadlResource to SadlResource (file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/model/DeclarationExtensions.xtend line : 346 column : 51)
WARNING:Unnecessary cast from XtextResource to XtextResource (file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/validation/SADLValidator.xtend line : 155 column : 21)
WARNING:Unnecessary cast from CompositeNodeWithSemanticElement to CompositeNodeWithSemanticElement (file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/validation/SADLValidator.xtend line : 158 colum
n : 34)
WARNING:Unnecessary cast from Name to Name (file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/validation/SADLValidator.xtend line : 258 column : 26)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':com.ge.research.sadl:generateXtext'.
> Xtext validation failed, see build log for details.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':com.ge.research.sadl:generateXtext'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: Xtext validation failed, see build log for details.
        at org.xtext.gradle.builder.XtextGradleBuilder.build(XtextGradleBuilder.java:210)
        at org.xtext.gradle.tasks.XtextGenerate.generate(XtextGenerate.java:149)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 30 more


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3m 1s
12 actionable tasks: 12 executed
Akoss-MacBook-Pro:sadlos2 akos.kitta$
```

This blocks #339.

**Comment by crapo** [comment]
@tuxji , I believe you made the logger changes? Could you please look at this and see if you can resolve the issue? Thanks.

**Comment by kittaakos** [comment]
Hint: we cannot use [`org.eclipse.xtext.builder.clustering.CurrentDescriptions`](https://github.com/eclipse/xtext-eclipse/blob/9961d23c5fcd513f8d83dc2e123acec1bf7f4430/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/clustering/CurrentDescriptions.java), it depends on Eclipse.

**Comment by tuxji** [comment]
@crapo, this is a tough problem to fix (by the way, it has nothing to do with logging).  I indeed used org.eclipse.xtext.builder.clustering.CurrentDescriptions in /sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/SADLRuntimeModule.xtend to prevent an exception when ExecuteCommand was building SADL files in the project (caused by the fact that ExecuteCommand was calling SADLStandaloneSetup().createInjectorAndDoEMFRegistration() to create and register the dependency injector).  This bug report (https://bugs.eclipse.org/bugs/show_bug.cgi?id=426212) describes the exception, IllegalStateException in ResourceSetBasedAllContainersStateProvider.getResourceSet(IResourceDescriptions), in more detail.  I followed the suggested workaround in that bug report to bind a custom MyResourceSetBasedAllContainersStateProvider in SadlRuntimeModule that adds code to getResourceSet(IResourceDescriptions context) to handle the case when CurrentDescriptions is passed into that method (hence avoiding the exception thrown by the base class method).  You can see the change here: https://github.com/crapo/sadlos2/pull/350/files#diff-f37a7773db20e901a02cb56b5705c135. 

@kittaakos, do you know a better way to create the dependency injector in ExecuteCommand that avoids calling SADLStandaloneSetup().createInjectorAndDoEMFRegistration()?  Then we could reverse the change to SadlRuntimeModule.xtend and its MANIFEST.MF which would remove the dependency on Eclipse.  I didn't know that CurrentDescriptions depends on Eclipse...

**Comment by tuxji** [comment]
Alternatively, ExecuteCommand could keep calling SADLStandaloneSetup().createInjectorAndDoEMFRegistration() if it also bound MyResourceSetBasedAllContainersStateProvider itself.  How can we move MyResourceSetBasedAllContainersStateProvider and its bind call from SadlRuntimeModule.xtend to ExecuteCommand.java, @kittaakos?

**Comment by kittaakos** [comment]
@tuxji, thanks for the info on this. I do not mind trying to fix the `CurrentDescriptions` issue but I need some input files and help to feed the CLI application. Otherwise, I cannot make sure I am not breaking it.

The bug you have referenced [also mentions](https://bugs.eclipse.org/bugs/show_bug.cgi?id=426212#c4) the following:
```
In our case I suspect the reason to be accidental execution of a StandaloneSetup in the Eclipse Workbench.
```

We cannot have a running Eclipse platform and call the StandaloneSetup at the same time. I will look into this. Please give me some instructions regarding the CLI application. (If you cannot share it here, please send me a mail.)

Thank you!

----

> SadlRuntimeModule.xtend to ExecuteCommand.java, @kittaakos?

We can subclass both the `SadlRuntimeModule` and `SADLStandaloneSetup` and use them only from the CLI app.

**Comment by kittaakos** [comment]
> We can subclass both the `SadlRuntimeModule` and `SADLStandaloneSetup` and use them only from the CLI app.

I have moved the customization into the CLI app. PR: https://github.com/crapo/sadlos2/pull/354
