### ISSUE TITLE
NPE in Jena based model processor with broken AST

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#355]
```
root ERROR SADL: com.ge.research.sadl.jena.PropertyWithoutRangeException: Property does not have a range

root ERROR SADL:        at com.ge.research.sadl.jena.JenaBasedSadlModelValidator.getType(JenaBasedSadlModelValidator.java:3137)
        at com.ge.research.sadl.jena.JenaBasedSadlModelValidator.getType(JenaBasedSadlModelValidator.java:3082)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:6695)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:6159)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3212)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:6334)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3216)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processBinaryExpressionByParts(JenaBasedSadlModelProcessor.java:4018)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3623)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3204)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processBinaryExpressionByParts(JenaBasedSadlModelProcessor.java:4026)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3623)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3204)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processStatement(JenaBasedSadlModelProcessor.java:3100)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processModelElement(JenaBasedSadlModelProcessor.java:1170)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.onValidate(JenaBasedSadlModelProcessor.java:1078)
        at com.ge.research.sadl.validation.ResourceValidator.doValidate(ResourceValidator.java:76)
        at com.ge.research.sadl.ide.validator.SadlIdeResourceValidator.doValidate(SadlIdeResourceValidator.java:67)

root ERROR SADL:        at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:72)
        at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
        at com.ge.research.sadl.validation.ResourceValidator.lambda$validate$0(ResourceValidator.java:56)
        at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:76)
        at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:58)
        at com.ge.research.sadl.ide.validator.SadlIdeResourceValidator.validate(SadlIdeResourceValidator.java:58)
        at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.validate(IncrementalBuilder.java:267)
        at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.lambda$launch$6(IncrementalBuilder.java:245)
        at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.lambda$executeClustered$1(ClusteringStorageAwareResourceLoader.java:77)
        at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
        at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:651)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
        at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
        at java.util.ArrayList.addAll(ArrayList.java:581)
        at com.google.common.collect.Iterables.addAll(Iterables.java:330)
        at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.executeClustered(ClusteringStorageAwareResourceLoader.java:80)
        at org.eclipse.xtext.build.BuildContext.executeClustered(BuildContext.java:55)
        at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.launch(IncrementalBuilder.java:252)
        at com.ge.research.sadl.ide.builder.SadlIdeIncrementalBuilder$SadlInternalStatefulIncrementalBuilder.launch(SadlIdeIncrementalBuilder.java:62)
        at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:400)
        at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:385)
        at org.eclipse.xtext.ide.server.ProjectManager.doBuild(ProjectManager.java:115)
        at com.ge.research.sadl.ide.lsp.extension.SadlProjectManager.doBuild(SadlProjectManager.java:50)
        at org.eclipse.xtext.ide.server.BuildManager.internalBuild(BuildManager.java:182)
        at org.eclipse.xtext.ide.server.BuildManager.lambda$submit$0(BuildManager.java:130)
        at org.eclipse.xtext.ide.server.WorkspaceManager.lambda$didChangeFiles$2(WorkspaceManager.java:174)
        at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$didChange$17(LanguageServerImpl.java:379)
        at org.eclipse.xtext.ide.server.concurrent.WriteRequest.run(WriteRequest.java:41)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

root ERROR SADL: com.ge.research.sadl.jena.PropertyWithoutRangeException: Property does not have a range
root ERROR SADL:

root ERROR SADL:        at com.ge.research.sadl.jena.JenaBasedSadlModelValidator.getType(JenaBasedSadlModelValidator.java:3137)
        at com.ge.research.sadl.jena.JenaBasedSadlModelValidator.getType(JenaBasedSadlModelValidator.java:3082)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:6695)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:6159)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3212)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:6334)

root ERROR SADL:        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3216)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processBinaryExpressionByParts(JenaBasedSadlModelProcessor.java:4026)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3623)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3204)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processBinaryExpressionByParts(JenaBasedSadlModelProcessor.java:4026)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3623)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3204)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processStatement(JenaBasedSadlModelProcessor.java:3100)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processModelElement(JenaBasedSadlModelProcessor.java:1170)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.onValidate(JenaBasedSadlModelProcessor.java:1078)
        at com.ge.research.sadl.validation.ResourceValidator.doValidate(ResourceValidator.java:76)
        at com.ge.research.sadl.ide.validator.SadlIdeResourceValidator.doValidate(SadlIdeResourceValidator.java:67)
        at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:72)
        at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)

root ERROR SADL:        at com.ge.research.sadl.validation.ResourceValidator.lambda$validate$0(ResourceValidator.java:56)
        at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:76)
        at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:58)
        at com.ge.research.sadl.ide.validator.SadlIdeResourceValidator.validate(SadlIdeResourceValidator.java:58)
        at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.validate(IncrementalBuilder.java:267)
        at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.lambda$launch$6(IncrementalBuilder.java:245)
        at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.lambda$executeClustered$1(ClusteringStorageAwareResourceLoader.java:77)
        at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
        at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:651)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
        at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
        at java.util.ArrayList.addAll(ArrayList.java:581)
        at com.google.common.collect.Iterables.addAll(Iterables.java:330)
        at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.executeClustered(ClusteringStorageAwareResourceLoader.java:80)
        at org.eclipse.xtext.build.BuildContext.executeClustered(BuildContext.java:55)
        at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.launch(IncrementalBuilder.java:252)
        at com.ge.research.sadl.ide.builder.SadlIdeIncrementalBuilder$SadlInternalStatefulIncrementalBuilder.launch(SadlIdeIncrementalBuilder.java:62)
        at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:400)
        at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:385)
        at org.eclipse.xtext.ide.server.ProjectManager.doBuild(ProjectManager.java:115)
        at com.ge.research.sadl.ide.lsp.extension.SadlProjectManager.doBuild(SadlProjectManager.java:50)
        at org.eclipse.xtext.ide.server.BuildManager.internalBuild(BuildManager.java:182)
        at org.eclipse.xtext.ide.server.BuildManager.lambda$submit$0(BuildManager.java:130)
        at org.eclipse.xtext.ide.server.WorkspaceManager.lambda$didChangeFiles$2(WorkspaceManager.java:174)
        at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$didChange$17(LanguageServerImpl.java:379)
        at org.eclipse.xtext.ide.server.concurrent.WriteRequest.run(WriteRequest.java:41)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
com.ge.research.sadl.jena.PropertyWithoutRangeException: Property does not have a range
        at com.ge.research.sadl.jena.JenaBasedSadlModelValidator.getType(JenaBasedSadlModelValidator.java:3137)
        at com.ge.research.sadl.jena.JenaBasedSadlModelValidator.getType(JenaBasedSadlModelValidator.java:3082)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:6695)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:6159)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3212)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:6334)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3216)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processBinaryExpressionByParts(JenaBasedSadlModelProcessor.java:4018)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3623)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3204)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processBinaryExpressionByParts(JenaBasedSadlModelProcessor.java:4018)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3623)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3204)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processBinaryExpressionByParts(JenaBasedSadlModelProcessor.java:4026)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3623)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processExpression(JenaBasedSadlModelProcessor.java:3204)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processStatement(JenaBasedSadlModelProcessor.java:3100)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.processModelElement(JenaBasedSadlModelProcessor.java:1170)
        at com.ge.research.sadl.jena.JenaBasedSadlModelProcessor.onValidate(JenaBasedSadlModelProcessor.java:1078)
        at com.ge.research.sadl.validation.ResourceValidator.doValidate(ResourceValidator.java:76)
        at com.ge.research.sadl.ide.validator.SadlIdeResourceValidator.doValidate(SadlIdeResourceValidator.java:67)
        at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:72)
        at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
        at com.ge.research.sadl.validation.ResourceValidator.lambda$validate$0(ResourceValidator.java:56)
        at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:76)
        at com.ge.research.sadl.validation.ResourceValidator.validate(ResourceValidator.java:58)
        at com.ge.research.sadl.ide.validator.SadlIdeResourceValidator.validate(SadlIdeResourceValidator.java:58)
        at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.validate(IncrementalBuilder.java:267)
        at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.lambda$launch$6(IncrementalBuilder.java:245)
        at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.lambda$executeClustered$1(ClusteringStorageAwareResourceLoader.java:77)
        at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
        at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:651)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
        at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
        at java.util.ArrayList.addAll(ArrayList.java:581)
        at com.google.common.collect.Iterables.addAll(Iterables.java:330)
        at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.executeClustered(ClusteringStorageAwareResourceLoader.java:80)
        at org.eclipse.xtext.build.BuildContext.executeClustered(BuildContext.java:55)
        at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.launch(IncrementalBuilder.java:252)
        at com.ge.research.sadl.ide.builder.SadlIdeIncrementalBuilder$SadlInternalStatefulIncrementalBuilder.launch(SadlIdeIncrementalBuilder.java:62)
        at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:400)
        at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:385)
        at org.eclipse.xtext.ide.server.ProjectManager.doBuild(ProjectManager.java:115)
        at com.ge.research.sadl.ide.lsp.extension.SadlProjectManager.doBuild(SadlProjectManager.java:50)
        at org.eclipse.xtext.ide.server.BuildManager.internalBuild(BuildManager.java:182)
        at org.eclipse.xtext.ide.server.BuildManager.lambda$submit$0(BuildManager.java:130)
        at org.eclipse.xtext.ide.server.WorkspaceManager.lambda$didChangeFiles$2(WorkspaceManager.java:174)
        at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$didChange$17(LanguageServerImpl.java:379)
        at org.eclipse.xtext.ide.server.concurrent.WriteRequest.run(WriteRequest.java:41)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

root ERROR SADL:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Steps to reproduce:
 - Import the [`coloring`](https://github.com/crapo/sadlos2/tree/master/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/sadl-extension/example-projects/coloring) example project.
 - Change `Shape` in the [`Shapes.sadl`](https://github.com/crapo/sadlos2/blob/1fb75682662792e87c563614d701a457380d37ff/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/sadl-extension/example-projects/coloring/Shapes.sadl#L3) to something else:
```
uri "http://sadl.org/Shapes.sadl".

Shasape is a class described by area with values of type float.
```

**Comment by crapo** [comment]
I followed the steps to reproduce but did not get the same error. Did discover dumb mistake in yesterday commit, JenaBasedSadlModelProcessor lines 7263, 7266, which I've fixed, but that was just passing in null argument. I do not go through the line of code in JenaBasedSadlModelValidator, line 3137. What's different?

**Comment by crapo** [comment]
I have tried again to reproduce in Eclipse-sadl and WebSADL without success. Closing as I think it is OBE.
