### ISSUE TITLE
[ci] npm publishing fails with node-gyp issue

### ISSUE THREAD

**Issue by kittaakos** [crapo/sadlos2#360]
```
error /home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/oniguruma: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/oniguruma
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.9.1 | linux | x64
gyp http GET https://nodejs.org/download/release/v8.9.1/node-v8.9.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.9.1/node-v8.9.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v8.9.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.9.1/SHASUMS256.txt
gyp info spawn /opt/pyenv/shims/python2
gyp info spawn args [ '/home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/oniguruma/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/travis/.node-gyp/8.9.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/travis/.node-gyp/8.9.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/travis/.node-gyp/8.9.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/oniguruma',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "/home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "/home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2783, in Load
    variables, includes, depth, check, True)
  File "/home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 399, in LoadTargetBuildFile
    includes, True, check)
  File "/home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 271, in LoadOneBuildFile
    aux_data, includes, check)
  File "/home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 308, in LoadBuildFileIncludesIntoDict
    LoadOneBuildFile(include, data, aux_data, None, False, check),
  File "/home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 251, in LoadOneBuildFile
    None)
  File "/home/travis/.node-gyp/8.9.1/include/node/common.gypi", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-101-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v8.9.1/bin/node" "/home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/travis/build/crapo/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/oniguruma
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by kittaakos** [comment]
The build is green now: https://travis-ci.org/crapo/sadlos2/builds/490093078.
