### ISSUE TITLE
highlight coloring in Equations/Externals

### ISSUE THREAD

**Issue by crapo** [crapo/sadlos2#57]
currently the argument variables are blue; would be nice if they were pink like other variables. Also need to consider color of name of equation/external...

**Comment by crapo** [comment]
I've made the variables pink. There is a related issue WRT equation/external names. In the model the name is a SadlResource, but if I click in the name and ask for references I get a null ptr exception:
java.lang.NullPointerException
	at com.ge.research.sadl.scoping.QualifiedNameProvider.getFullyQualifiedName(QualifiedNameProvider.java:48)
	at org.eclipse.xtext.ui.editor.findrefs.ReferenceQueryExecutor.getElementName(ReferenceQueryExecutor.java:84)
	at org.eclipse.xtext.ui.editor.findrefs.ReferenceQueryExecutor.getLabel(ReferenceQueryExecutor.java:70)
	at org.eclipse.xtext.ui.editor.findrefs.ReferenceQueryExecutor.init(ReferenceQueryExecutor.java:105)
	at org.eclipse.xtext.ui.editor.findrefs.FindReferencesHandler.getQueryExecutor(FindReferencesHandler.java:74)
	at org.eclipse.xtext.ui.editor.findrefs.FindReferencesHandler.findReferences(FindReferencesHandler.java:64)
	at org.eclipse.xtext.ui.editor.findrefs.FindReferencesHandler$1.process(FindReferencesHandler.java:53)
	at org.eclipse.xtext.ui.editor.findrefs.FindReferencesHandler$1.process(FindReferencesHandler.java:1)

If the equation is an instance where declared, it should be an instance where referenced... This is presumably independent of how it is colored in highlighting...

**Comment by svenefftinge** [comment]
That NPE is thrown because there is Equations are not properly linked, yet. Ticket #59 is about that.
